version: 0.2

phases:
 build:
   commands:
     - echo Build started on `date`
     - cd frontend
     - npm install
     - npm run build     
 post_build:
   commands:
     - echo Build completed on `date`   
     - aws s3 cp frontend/build/ s3://demchenko.oleksandr-fe-hosting-lab2/ --recursive
artifacts:
  base-directory: frontend/build
  files:
    - '**/*'